### PR TITLE
feat: Added brotli compression

### LINKED ISSUE #66: Support brotli compression?
All the major browsers now support Brotli compression, may you implement support for it?

http://caniuse.com/#search=brotli

### PR DESCRIPTION
**Pull request by FezVrasta**
close #66

I deployed the fork on now.sh if you want to try it:

https://badge-size.now.sh/https://unpkg.com/popper.js/dist/popper.min.js?compression=brotli

### CODE REVIEW

**Comment by ngryman** [comment]
@FezVrasta awesome! Thanks for this neat addition :clap:

Could you just fix the 2 tests:
 1. The first one seems to be related with `brotli` having a smaller size that checked in the test.
 2. The second one change the current behavior, which is better! Now when specifying an unknown compression we'll have `size-unknown compression` instead of `gzip size-unknown compression`, which makes perfect sense. Could you just remove the `gzip-`?

Thanks!

**Comment by FezVrasta** [comment]
I don't think I understand how am I supposed to fix the point 2, any guidance?

**Comment by FezVrasta** [comment]
Done

**Comment by ngryman** [comment]
Thanks! :tada:

**Comment by FezVrasta** [comment]
Do you need to perform a new deploy to add the feature?

**Comment by ngryman** [comment]
Yes but Heroku seems to [have problems right now](https://status.heroku.com/) to promote my staging to production. I'll just gonna wait that everything goes back to normal.

**Pull request merged**
